// ─── WEEKLY DIGEST EMAIL ──────────────────────────────────────────────────────

/**
 * Sends a weekly HTML digest of all flagged jobs to CONFIG.DIGEST_EMAIL.
 * Designed to run every Monday at 9 AM IST.
 */
function Digest_sendWeekly() {
  const jobs = Sheet_getFlaggedJobs();

  if (jobs.length === 0) {
    console.log('Digest: no flagged jobs this week — skipping email.');
    return;
  }

  const top5     = jobs.slice(0, 5);
  const subject  = `Job Digest — ${top5.length} role${top5.length > 1 ? 's' : ''} to review (${Digest_weekLabel()})`;
  const htmlBody = Digest_buildHtml(jobs);

  MailApp.sendEmail({
    to:       CONFIG.DIGEST_EMAIL,
    subject,
    htmlBody,
  });

  console.log(`Digest sent to ${CONFIG.DIGEST_EMAIL}: ${jobs.length} flagged roles.`);
}

// ─── HTML BUILDER ─────────────────────────────────────────────────────────────

function Digest_buildHtml(jobs) {
  const top5    = jobs.slice(0, 5);
  const rest    = jobs.slice(5);
  const weekStr = Digest_weekLabel();

  const rows = top5.map((job) => Digest_jobRow(job)).join('\n');
  const restSection = rest.length > 0
    ? `<p style="color:#666;font-size:13px;margin-top:24px;">
         + ${rest.length} more flagged role${rest.length > 1 ? 's' : ''} in the sheet.
       </p>`
    : '';

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:Arial,sans-serif;color:#222;max-width:680px;margin:0 auto;padding:24px;">

  <h2 style="color:#1a1a1a;border-bottom:2px solid #4CAF50;padding-bottom:8px;">
    Job Digest — ${weekStr}
  </h2>

  <p style="color:#555;margin-bottom:24px;">
    ${jobs.length} role${jobs.length > 1 ? 's' : ''} scored 70+ this week.
    Top ${top5.length} shown below. Open the sheet for full details.
  </p>

  ${rows}

  ${restSection}

  <hr style="border:none;border-top:1px solid #eee;margin:32px 0;">
  <p style="color:#999;font-size:12px;">
    Generated by job-agent. To tailor a resume, paste the JD into Claude with the saved prompt.
    Mark a role as "applied" or "rejected" in the Status column to track it.
  </p>

</body>
</html>`.trim();
}

function Digest_jobRow(job) {
  const scoreColor = job.score >= 85 ? '#2e7d32' : job.score >= 70 ? '#4CAF50' : '#888';
  const remoteTag  = job.remoteConfirmed === 'yes'
    ? '<span style="background:#e8f5e9;color:#2e7d32;padding:2px 6px;border-radius:3px;font-size:11px;">Remote confirmed</span>'
    : job.remoteConfirmed === 'verify'
    ? '<span style="background:#fff8e1;color:#f57f17;padding:2px 6px;border-radius:3px;font-size:11px;">Verify remote</span>'
    : '';

  const keywords = (job.topKeywords || '')
    .split(',')
    .map((k) => k.trim())
    .filter(Boolean)
    .map((k) => `<span style="background:#e3f2fd;color:#1565c0;padding:1px 5px;border-radius:3px;font-size:11px;">${k}</span>`)
    .join(' ');

  const salary  = job.salary   ? `<span style="color:#555;font-size:13px;">  ${job.salary}</span>` : '';
  const watchOut = job.watchOut ? `<p style="color:#e65100;font-size:12px;margin:4px 0 0;">Watch out: ${job.watchOut}</p>` : '';

  return `
<div style="border:1px solid #ddd;border-radius:6px;padding:16px;margin-bottom:16px;">

  <table width="100%" cellpadding="0" cellspacing="0">
    <tr>
      <td>
        <strong style="font-size:16px;">${Digest_esc(job.title)}</strong>
        <span style="color:#555;font-size:14px;"> at ${Digest_esc(job.company)}</span>
      </td>
      <td align="right">
        <span style="font-size:22px;font-weight:bold;color:${scoreColor};">${job.score}</span>
        <span style="color:#888;font-size:12px;">/100</span>
      </td>
    </tr>
  </table>

  <p style="color:#555;font-size:13px;margin:6px 0;">
    ${Digest_esc(job.location)} ${salary} &nbsp; ${remoteTag}
    &nbsp; <span style="color:#999;font-size:12px;">via ${Digest_esc(job.source)} &bull; ${job.postedDate}</span>
  </p>

  <p style="font-size:13px;margin:8px 0;">${Digest_esc(job.fitSummary)}</p>

  <p style="margin:6px 0;">${keywords}</p>
  <p style="margin:6px 0;">Resume version: <strong>${job.resumeVersion}</strong></p>
  ${watchOut}

  <p style="margin:12px 0 0;">
    <a href="${job.applyUrl}"
       style="background:#4CAF50;color:#fff;padding:8px 16px;text-decoration:none;border-radius:4px;font-size:13px;">
      Apply now
    </a>
  </p>

</div>`.trim();
}

function Digest_weekLabel() {
  const now = new Date();
  return now.toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'Asia/Kolkata' });
}

function Digest_esc(str) {
  return (str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
